### PR TITLE
service null check

### PR DESCRIPTION
**Pull request by Cool04ek**

### CODE REVIEW

**Comment by VictorAlbertos** [comment]
This is not the same implementation performed against the branch 1.x.

Why did you add `@TargetApi`? The last time I checked it was suggested to use the deprecated one. In any case,  it is not the same implementation as the branch 1.x. Please, refactor your changes to be the same as the 1.x brand and commit them again.

And, next time, please don't format the code. Try to be as minimal as possible with your changes.

Thanks.

**Comment by Cool04ek** [comment]
Of course. I've rolled back those changes and provided update. Please check

**Comment by VictorAlbertos** [comment]
Thanks @Cool04ek. I'm gonna to release a new version right now.

**Comment by VictorAlbertos** [comment]
Done!

**Pull request merged**
